version: '3.8'

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80" #iz dokera v real port
    volumes:
      - ./.dockerfiles/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # iz kakoi papki v ubuntu sozdat fail s nastroikoi
      - ./web:/var/www/app # iz kakoi papki mi budem 4itat nawe prilozhenie laravel (v etom slu4ae iz kornja)
    depends_on:
      - mysql
      - php
  php:
    build:
      context: .dockerfiles/php # papka gde iskat config dlja ustanovki php v container
      dockerfile: php.Dockerfile # nazvanie faila
    volumes:
      - ./web:/var/www/app
  mysql: # eto zhe nazvanie budet ispolzovatsa v .env (laravel) dla hosta mysql
    image: mysql:8.0
    ports:
      - "3316:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    env_file:
      - .dockerfiles/mysql/conf.env
  artisan:
    build: 
      context: ./.dockerfiles/php
      dockerfile: php.Dockerfile
    volumes:
      - ./web:/var/www/app
    #iz za togo 4to mi ne sozdali noviy fail, ispolzuem php.Dockerfile s entrypoint kotoriy obratitsa k php i vizovit artisan
    entrypoint: ["php", "/var/www/app/artisan"]
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  node:
    build: 
      context: ./.dockerfiles/node
      dockerfile: node.Dockerfile
    tty: true
    ports: 
      - "5173:3000"
    volumes:
      - ./web/:/var/www/app

volumes:
  mysql_data:
  
