version: '3.8'

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./.dockerfiles/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web:/var/www/app
    depends_on:
      - mysql
      - php
  php:
    build:
      context: .dockerfiles/php
      dockerfile: php.Dockerfile
    volumes:
      - ./web:/var/www/app
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    env_file:
      - .dockerfiles/mysql/conf.env

volumes:
  mysql_data:
  
