openapi: 3.0.0
info:
  title: Wether Stations API
  version: 1.0.0
paths:
  /api/stations:
    get:
      summary: Get all stations
      responses:
        '200':
          description: A list of stations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    station_id:
                      type: string
                    name:
                      type: string
      security:
        - bearerAuth: []
  /api/stations/{id}:
    get:
      summary: Get station by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Station details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  station_id:
                    type: string
                  name:
                    type: string
                  wmo_id:
                    type: integer
                  begin_date:
                    type: string
                    format: date-time
                  end_date:
                    type: string
                    format: date-time
                  latitude:
                    type: number
                    format: float
                  longitude:
                    type: number
                    format: float
                  gauss1:
                    type: number
                    format: float
                  gauss2:
                    type: number
                    format: float
                  geogr1:
                    type: number
                    format: float
                  geogr2:
                    type: number
                    format: float
                  elevation:
                    type: number
                    format: float
                  elevation_pressure:
                    type: number
                    format: float
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: STRING
